<?php

class chainModel {

    public function getChains() {
        $chains = [
            "5930" => [
                "CHAIN_NAME" => "Canadian E. Coast",
                "TOWER_NAME" => "Caribou, ME",
                "LAT"        => "46 48 27.305  N",
                "LON"        => "67 55 37.159 W",
                "SLAVES"     => [
                    [
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Nantucket, MA",
                        "LAT"          => "41 15 12.046 N",
                        "LON"          => "69 58 38.536 W",
                        "DELAY"        => 11000,
                    ],
                    [
                        "SLAVE_LETTER" => "Y",
                        "TOWER_NAME"   => "Cape Race, Newfoundland",
                        "LAT"          => "46 46 32.286 N",
                        "LON"          => "53 10 27.606 W",
                        "DELAY"        => 25000,
                    ],
                    [
                        "SLAVE_LETTER" => "Z",
                        "TOWER_NAME"   => "Fox Harbor, Newfoundland",
                        "LAT"          => "52 22 35.252 N",
                        "LON"          => "55 42 27.862 W",
                        "DELAY"        => 38000,
                    ],
                ],
            ],
            "5990" => [
                "CHAIN_NAME" => "Canadian W. Coast",
                "TOWER_NAME" => "Williams Lake, BC",
                "LAT"        => "51 57 58.876 N",
                "LON"        => "122 22 01.686 W",
                "SLAVES"     => [
                    [
                        "CHAIN_NAME"   => "Canadian W. Coast",
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Shoal Cove, AK",
                        "LAT"          => "55 26 20.940 N",
                        "LON"          => "131 15 19.094 W",
                        "DELAY"        => 11000,
                    ],
                    [
                        "CHAIN_NAME"   => "Canadian W. Coast",
                        "SLAVE_LETTER" => "Y",
                        "TOWER_NAME"   => "George, WA",
                        "LAT"          => "47 03 48.096 N",
                        "LON"          => "119 44 38.976 W",
                        "DELAY"        => 27000,
                    ],
                    [
                        "CHAIN_NAME"   => "Canadian W. Coast",
                        "SLAVE_LETTER" => "Z",
                        "TOWER_NAME"   => "Port Hardy, B.C.",
                        "LAT"          => "50 36 29.830 N",
                        "LON"          => "127 21 28.489 W",
                        "DELAY"        => 41000,
                    ],
                ],
            ],
            "7270" => [
                "CHAIN_NAME" => "Newfoundland E. Coast",
                "TOWER_NAME" => "Comfort Cove, Newfoundland",
                "LAT"        => "49 19 53.57 N",
                "LON"        => "54 51 42.57 W",
                "SLAVES"     => [
                    [
                        "CHAIN_NAME"   => "Newfoundland E. Coast",
                        "SLAVE_LETTER" => "W",
                        "TOWER_NAME"   => "Cape Race, Newfoundland",
                        "LAT"          => "46 46 32.286 N",
                        "LON"          => "53 10 27.606 W",
                        "DELAY"        => 25000,
                    ],
                    [
                        "CHAIN_NAME"   => "Newfoundland E. Coast",
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Fox Harbor, Newfoundland",
                        "LAT"          => "52 22 35.252 N",
                        "LON"          => "55 42 27.862 W",
                        "DELAY"        => 38000,
                    ],
                ],
            ],
            "7960" => [
                "CHAIN_NAME" => "Gulf of Alaska",
                "TOWER_NAME" => "Tok, AK",
                "LAT"        => "63 19 42.884 N",
                "LON"        => "142 48 31.346 W",
                "SLAVES"     => [
                    [
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Kodiak, AK",
                        "LAT"          => "57 26 20.30 N",
                        "LON"          => "152 22 10.65 W",
                        "DELAY"        => 11000,
                    ],
                    [
                        "SLAVE_LETTER" => "Y",
                        "TOWER_NAME"   => "Shoal Cove, AK",
                        "LAT"          => "55 26 20.940 N",
                        "LON"          => "131 15 19.094 W",
                        "DELAY"        => 26000,
                    ],
                    [
                        "SLAVE_LETTER" => "Z",
                        "TOWER_NAME"   => "Port Clarence, AK",
                        "LAT"          => "65 14 40.372 N",
                        "LON"          => "166 53 11.996 W",
                        "DELAY"        => 45000,
                    ],
                ],
            ],
            "7980" => [
                "CHAIN_NAME" => "Southeast. U.S.",
                "TOWER_NAME" => "Malone, FL",
                "LAT"        => "30 59 38.870 N",
                "LON"        => "85 10 08.751 W",
                "SLAVES"     => [
                    [
                        "CHAIN_NAME"   => "Southeast. U.S.",
                        "SLAVE_LETTER" => "W",
                        "TOWER_NAME"   => "Grangeville, LA",
                        "LAT"          => "30 43 33.149 N",
                        "LON"          => "90 49 59.539 W",
                        "DELAY"        => 11000,
                    ],
                    [
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Raymondville, TX",
                        "LAT"          => "26 31 55.141 N",
                        "LON"          => "97 49 59.539 W",
                        "DELAY"        => 23000,
                    ],
                    [
                        "SLAVE_LETTER" => "Y",
                        "TOWER_NAME"   => "Jupiter, FL",
                        "LAT"          => "27 01 58.63 N",
                        "LON"          => "80 06 52.97 W",
                        "DELAY"        => 43000,
                    ],
                    [
                        "SLAVE_LETTER" => "Z",
                        "TOWER_NAME"   => "Carolina Beach, NC",
                        "LAT"          => "34 03 46.17 N",
                        "LON"          => "77 54 46.21 W",
                        "DELAY"        => 59000,
                    ],
                ],
            ],
            "8290" => [
                "CHAIN_NAME" => "N. Central U.S.",
                "TOWER_NAME" => "Havre, MT",
                "LAT"        => "48 44 38.589 N",
                "LON"        => "109 58 53.613 W",
                "SLAVES"     => [
                    [
                        "SLAVE_LETTER" => "W",
                        "TOWER_NAME"   => "Baudette, MN",
                        "LAT"          => "48 36 49.947 N",
                        "LON"          => "94 33 17.915 W",
                        "DELAY"        => 11000,
                    ],
                    [
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Gillette, WY",
                        "LAT"          => "44 00 11.305 N",
                        "LON"          => "105 37 23.895 W",
                        "DELAY"        => 27000,
                    ],
                    [
                        "SLAVE_LETTER" => "Y",
                        "TOWER_NAME"   => "Williams Lake, BC",
                        "LAT"          => "51 57 58.876 N",
                        "LON"          => "122 22 01.686 W",
                        "DELAY"        => 42000,
                    ],
                ],
            ],
            "8970" => [
                "CHAIN_NAME" => "Great Lakes",
                "TOWER_NAME" => "Dana, IN",
                "LAT"        => "39 51 07.658 N",
                "LON"        => "87 29 11.586 W",
                "SLAVES"     => [
                    [
                        "SLAVE_LETTER" => "W",
                        "TOWER_NAME"   => "Malone, FL",
                        "LAT"          => "30 59 38.870 N",
                        "LON"          => "85 10 08.751 W",
                        "DELAY"        => 11000,
                    ],
                    [
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Seneca, NY",
                        "LAT"          => "42 42 50.716 N",
                        "LON"          => "76 49 33.308 W",
                        "DELAY"        => 28000,
                    ],
                    [
                        "SLAVE_LETTER" => "W",
                        "TOWER_NAME"   => "Baudette, MN",
                        "LAT"          => "48 36 49.947 N",
                        "LON"          => "94 33 17.915 W",
                        "DELAY"        => 44000,
                    ],
                    [
                        "SLAVE_LETTER" => "Z",
                        "TOWER_NAME"   => "Boise City, OK",
                        "LAT"          => "36 30 20.783 N",
                        "LON"          => "102 53 59.487 W",
                        "DELAY"        => 59000,
                    ],
                ],
            ],
            "9610" => [
                "CHAIN_NAME" => "S. Central U.S.",
                "TOWER_NAME" => "Boise City, OK",
                "LAT"        => "36 30 20.783 N",
                "LON"        => "102 53 59.487 W",
                "SLAVES"     => [
                    [
                        "SLAVE_LETTER" => "V",
                        "TOWER_NAME"   => "Gillette, WY",
                        "LAT"          => "44 00 11.305 N",
                        "LON"          => "105 37 23.895 W",
                        "DELAY"        => 11000,
                    ],
                    [
                        "SLAVE_LETTER" => " W",
                        "TOWER_NAME"   => "Searchlight, NV",
                        "LAT"          => "35 19 18.305 N",
                        "LON"          => "114 48 16.881 W",
                        "DELAY"        => 25000,
                    ],
                    [
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Las Cruces, NM",
                        "LAT"          => "32 04 18.130 N",
                        "LON"          => "106 52 04.388 W",
                        "DELAY"        => 40000,
                    ],
                    [
                        "SLAVE_LETTER" => "Y",
                        "TOWER_NAME"   => "Raymondville, TX",
                        "LAT"          => "26 31 55.141 N",
                        "LON"          => "97 49 59.539 W",
                        "DELAY"        => 52000,
                    ],
                    [
                        "SLAVE_LETTER" => "Z",
                        "TOWER_NAME"   => "Grangeville, LA",
                        "LAT"          => "30 43 33.149 N",
                        "LON"          => "90 49 59.539 W",
                        "DELAY"        => 65000,
                    ],
                ],
            ],
            "9940" => [
                "CHAIN_NAME" => "Western U.S.",
                "TOWER_NAME" => "Fallon, NV",
                "LAT"        => "39 33 06.740 N",
                "LON"        => "118 49 55.816 W",
                "SLAVES"     => [
                    [
                        "SLAVE_LETTER" => "W",
                        "TOWER_NAME"   => "George, WA",
                        "LAT"          => "47 03 48.096 N",
                        "LON"          => "119 44 38.976 W",
                        "DELAY"        => 11000,
                    ],
                    [
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Middletown, CA",
                        "LAT"          => "38 46 57.110 N",
                        "LON"          => "122 29 43.976 W",
                        "DELAY"        => 27000,
                    ],
                    [
                        "SLAVE_LETTER" => "Y",
                        "TOWER_NAME"   => "Searchlight, NV",
                        "LAT"          => "35 19 18.305 N",
                        "LON"          => "114 48 16.881 W",
                        "DELAY"        => 40000,
                    ],
                ],
            ],
            "9960" => [
                "CHAIN_NAME" => "Northeast U.S.",
                "TOWER_NAME" => "Seneca, NY",
                "LAT"        => "42 42 50.716 N",
                "LON"        => "76 49 33.308 W",
                "SLAVES"     => [
                    [
                        "SLAVE_LETTER" => "W",
                        "TOWER_NAME"   => "Caribou, ME",
                        "LAT"          => "46 48 27.305 N",
                        "LON"          => "67 55 37.159 W",
                        "DELAY"        => 11000,
                    ],
                    [
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Nantucket, MA",
                        "LAT"          => "41 15 12.046 N",
                        "LON"          => "69 58 38.536 W",
                        "DELAY"        => 25000,
                    ],
                    [
                        "SLAVE_LETTER" => "Y",
                        "TOWER_NAME"   => "Carolina Beach, NC",
                        "LAT"          => "34 03 46.17 N",
                        "LON"          => "77 54 46.21 W",
                        "DELAY"        => 39000,
                    ],
                    [
                        "SLAVE_LETTER" => "Z",
                        "TOWER_NAME"   => "Dana, IN",
                        "LAT"          => "39 51 07.658 N",
                        "LON"          => "87 29 11.586 W",
                        "DELAY"        => 54000,
                    ],
                ],
            ],
            "9990" => [
                "CHAIN_NAME" => "N. Pacific",
                "TOWER_NAME" => "St Paul, Pribilof Island, AK",
                "LAT"        => "57 09 12.350 N",
                "LON"        => "170 15 06.245 W",
                "SLAVES"     => [
                    [
                        "SLAVE_LETTER" => "X",
                        "TOWER_NAME"   => "Attu Island, AK",
                        "LAT"          => "52 49 44.134 N",
                        "LON"          => "173 10 49.528 E",
                        "DELAY"        => 11000,
                    ],
                    [
                        "SLAVE_LETTER" => "Y",
                        "TOWER_NAME"   => "Port Clarence, AK",
                        "LAT"          => "65 14 40.372 N",
                        "LON"          => "166 53 11.996 W",
                        "DELAY"        => 29000,
                    ],
                    [
                        "SLAVE_LETTER" => "Z",
                        "TOWER_NAME"   => "Kodiak, AK",
                        "LAT"          => "57 26 20.30 N",
                        "LON"          => "152 22 10.65 W",
                        "DELAY"        => 43000,
                    ],
                ],
            ],
        ];

        return $chains;
    }
}